name: SubCraft
main: com.mentonica.SubCraft.Boot
version: 2.0
commands:
   sckey:
      description: Sets the key for SubCraft
      usage: /<command> [key of 25 characters]
      permission: subcraft.basic
      permission-message: You don't have <permission>

   screfresh:
      description: Refreshes the SubCraft purchases
      usage: /<command>
      permission: subcraft.refresh
      permission-message: You don't have <permission>
