name: SubCraft
main: com.mentonica.SubCraft.Boot
version: 2.0
commands:
   subcraft:
      description: This is a demo command.
      usage: /<command> [player]
      permission: GroupManager.basic
      permission-message: You don't have <permission>